config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index', to: 'home#index'
  get 'home/about', to: 'home#about'

  get 'posts/index', to:'posts#index'
  post 'posts', to:'posts#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @new_post = Post.new
  end

  def create
    @post = Post.new(params[:post].permit(:name, :email, :body))
    @post.save
    redirect_to posts_index_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/about.html.erb
<div class="main-about">
  <p>this is home#about</p>

  <p>自殺サークル</p>
  <p>紀子の食卓</p>
</div>

app/views/home/index.html.erb
<div class="s-maru red">
  <% 54.times do %>
    <div class="circle red">
    </div>
  <% end %>
</div>

<div class="s-maru white">
  <% 100.times do %>
    <div class="circle white">
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Haikyo.com</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id='<%= "#{controller.controller_name}" %>'>
    <header>
    </header>
    <div class="container">
      <%= yield %>
    </div>

    <div id="footer">
      <div class="box">
        <%= link_to(posts_index_path) do %>
          <div id="red-circle-button" class="red circle">
          </div>
        <% end %>

        <%= link_to(home_index_path) do %>
        <div id="yellow-ciecle-button" class="yellow circle">
        </div>
        <% end %>

        <%= link_to(home_about_path) do %>
        <div id="white-circle-button" class="white circle">
        </div>
        <% end %>

      </div>
    </div>

  </body>
</html>

app/views/posts/index.html.erb
<h1>haikyo.com</h1>
<%= form_for :post, url: posts_path do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>
<p><%= f.label :email %></p>
<p><%= f.text_field :email %></p>
<p><%= f.label :body %></p>
<p><%= f.text_area :body %></p>
<%= f.submit %>
<% end %>

<% @posts.each do |post| %>
  <ul>
    <li>
      <%= post.id %><%= post.body %>
    </li>
  </ul>
<% end %>